config/routes.rb
Rails.application.routes.draw do
  resources :opinions
  resources :security_elements
  resources :maintenances
  resources :rules
  resources :cyclists
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/opinion.rb
class Opinion < ApplicationRecord
end

app/controllers/opinions_controller.rb
class OpinionsController < ApplicationController
  before_action :set_opinion, only: [:show, :edit, :update, :destroy]

  # GET /opinions
  # GET /opinions.json
  def index
    @opinions = Opinion.all
  end

  # GET /opinions/1
  # GET /opinions/1.json
  def show
  end

  # GET /opinions/new
  def new
    @opinion = Opinion.new
  end

  # GET /opinions/1/edit
  def edit
  end

  # POST /opinions
  # POST /opinions.json
  def create
    @opinion = Opinion.new(opinion_params)

    respond_to do |format|
      if @opinion.save
        format.html { redirect_to @opinion, notice: 'Opinion was successfully created.' }
        format.json { render :show, status: :created, location: @opinion }
      else
        format.html { render :new }
        format.json { render json: @opinion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /opinions/1
  # PATCH/PUT /opinions/1.json
  def update
    respond_to do |format|
      if @opinion.update(opinion_params)
        format.html { redirect_to @opinion, notice: 'Opinion was successfully updated.' }
        format.json { render :show, status: :ok, location: @opinion }
      else
        format.html { render :edit }
        format.json { render json: @opinion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /opinions/1
  # DELETE /opinions/1.json
  def destroy
    @opinion.destroy
    respond_to do |format|
      format.html { redirect_to opinions_url, notice: 'Opinion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_opinion
      @opinion = Opinion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def opinion_params
      params.require(:opinion).permit(:usuario, :fecha, :tipo, :asunto, :texto)
    end
end

app/helpers/opinions_helper.rb
module OpinionsHelper
end

app/views/opinions/_form.html.erb
<%= form_for(opinion) do |f| %>
  <% if opinion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(opinion.errors.count, "error") %> prohibited this opinion from being saved:</h2>

      <ul>
      <% opinion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :usuario %>
    <%= f.text_field :usuario %>
  </div>

  <div class="field">
    <%= f.label :fecha %>
    <%= f.date_select :fecha %>
  </div>

  <div class="field">
    <%= f.label :tipo %>
    <%= f.text_field :tipo %>
  </div>

  <div class="field">
    <%= f.label :asunto %>
    <%= f.text_field :asunto %>
  </div>

  <div class="field">
    <%= f.label :texto %>
    <%= f.text_area :texto %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/opinions/edit.html.erb
<h1>Editing Opinion</h1>

<%= render 'form', opinion: @opinion %>

<%= link_to 'Show', @opinion %> |
<%= link_to 'Back', opinions_path %>

app/views/opinions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Opinions</h1>

<table>
  <thead>
    <tr>
      <th>Usuario</th>
      <th>Fecha</th>
      <th>Tipo</th>
      <th>Asunto</th>
      <th>Texto</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @opinions.each do |opinion| %>
      <tr>
        <td><%= opinion.usuario %></td>
        <td><%= opinion.fecha %></td>
        <td><%= opinion.tipo %></td>
        <td><%= opinion.asunto %></td>
        <td><%= opinion.texto %></td>
        <td><%= link_to 'Show', opinion %></td>
        <td><%= link_to 'Edit', edit_opinion_path(opinion) %></td>
        <td><%= link_to 'Destroy', opinion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Opinion', new_opinion_path %>

app/views/opinions/new.html.erb
<h1>New Opinion</h1>

<%= render 'form', opinion: @opinion %>

<%= link_to 'Back', opinions_path %>

app/views/opinions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Usuario:</strong>
  <%= @opinion.usuario %>
</p>

<p>
  <strong>Fecha:</strong>
  <%= @opinion.fecha %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @opinion.tipo %>
</p>

<p>
  <strong>Asunto:</strong>
  <%= @opinion.asunto %>
</p>

<p>
  <strong>Texto:</strong>
  <%= @opinion.texto %>
</p>

<%= link_to 'Edit', edit_opinion_path(@opinion) %> |
<%= link_to 'Back', opinions_path %>