config/routes.rb
Rails.application.routes.draw do
  resources :opinions
  resources :security_elements
  resources :maintenances
  resources :rules
  resources :cyclists
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/security_element.rb
class SecurityElement < ApplicationRecord
end

app/controllers/security_elements_controller.rb
class SecurityElementsController < ApplicationController
  before_action :set_security_element, only: [:show, :edit, :update, :destroy]

  # GET /security_elements
  # GET /security_elements.json
  def index
    @security_elements = SecurityElement.all
  end

  # GET /security_elements/1
  # GET /security_elements/1.json
  def show
  end

  # GET /security_elements/new
  def new
    @security_element = SecurityElement.new
  end

  # GET /security_elements/1/edit
  def edit
  end

  # POST /security_elements
  # POST /security_elements.json
  def create
    @security_element = SecurityElement.new(security_element_params)

    respond_to do |format|
      if @security_element.save
        format.html { redirect_to @security_element, notice: 'Security element was successfully created.' }
        format.json { render :show, status: :created, location: @security_element }
      else
        format.html { render :new }
        format.json { render json: @security_element.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /security_elements/1
  # PATCH/PUT /security_elements/1.json
  def update
    respond_to do |format|
      if @security_element.update(security_element_params)
        format.html { redirect_to @security_element, notice: 'Security element was successfully updated.' }
        format.json { render :show, status: :ok, location: @security_element }
      else
        format.html { render :edit }
        format.json { render json: @security_element.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /security_elements/1
  # DELETE /security_elements/1.json
  def destroy
    @security_element.destroy
    respond_to do |format|
      format.html { redirect_to security_elements_url, notice: 'Security element was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_security_element
      @security_element = SecurityElement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def security_element_params
      params.require(:security_element).permit(:descripcion, :nombre, :reglamentario)
    end
end

app/helpers/security_elements_helper.rb
module SecurityElementsHelper
end

app/views/security_elements/_form.html.erb
<%= form_for(security_element) do |f| %>
  <% if security_element.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(security_element.errors.count, "error") %> prohibited this security_element from being saved:</h2>

      <ul>
      <% security_element.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :descripcion %>
    <%= f.text_area :descripcion %>
  </div>

  <div class="field">
    <%= f.label :nombre %>
    <%= f.text_field :nombre %>
  </div>

  <div class="field">
    <%= f.label :reglamentario %>
    <%= f.text_field :reglamentario %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/security_elements/edit.html.erb
<h1>Editing Security Element</h1>

<%= render 'form', security_element: @security_element %>

<%= link_to 'Show', @security_element %> |
<%= link_to 'Back', security_elements_path %>

app/views/security_elements/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Security Elements</h1>

<table>
  <thead>
    <tr>
      <th>Descripcion</th>
      <th>Nombre</th>
      <th>Reglamentario</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @security_elements.each do |security_element| %>
      <tr>
        <td><%= security_element.descripcion %></td>
        <td><%= security_element.nombre %></td>
        <td><%= security_element.reglamentario %></td>
        <td><%= link_to 'Show', security_element %></td>
        <td><%= link_to 'Edit', edit_security_element_path(security_element) %></td>
        <td><%= link_to 'Destroy', security_element, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Security Element', new_security_element_path %>

app/views/security_elements/new.html.erb
<h1>New Security Element</h1>

<%= render 'form', security_element: @security_element %>

<%= link_to 'Back', security_elements_path %>

app/views/security_elements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descripcion:</strong>
  <%= @security_element.descripcion %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @security_element.nombre %>
</p>

<p>
  <strong>Reglamentario:</strong>
  <%= @security_element.reglamentario %>
</p>

<%= link_to 'Edit', edit_security_element_path(@security_element) %> |
<%= link_to 'Back', security_elements_path %>