config/routes.rb
Rails.application.routes.draw do
  resources :opinions
  resources :security_elements
  resources :maintenances
  resources :rules
  resources :cyclists
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cyclist.rb
class Cyclist < ApplicationRecord
end

app/controllers/cyclists_controller.rb
class CyclistsController < ApplicationController
  before_action :set_cyclist, only: [:show, :edit, :update, :destroy]

  # GET /cyclists
  # GET /cyclists.json
  def index
    @cyclists = Cyclist.all
  end

  # GET /cyclists/1
  # GET /cyclists/1.json
  def show
  end

  # GET /cyclists/new
  def new
    @cyclist = Cyclist.new
  end

  # GET /cyclists/1/edit
  def edit
  end

  # POST /cyclists
  # POST /cyclists.json
  def create
    @cyclist = Cyclist.new(cyclist_params)

    respond_to do |format|
      if @cyclist.save
        format.html { redirect_to @cyclist, notice: 'Cyclist was successfully created.' }
        format.json { render :show, status: :created, location: @cyclist }
      else
        format.html { render :new }
        format.json { render json: @cyclist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cyclists/1
  # PATCH/PUT /cyclists/1.json
  def update
    respond_to do |format|
      if @cyclist.update(cyclist_params)
        format.html { redirect_to @cyclist, notice: 'Cyclist was successfully updated.' }
        format.json { render :show, status: :ok, location: @cyclist }
      else
        format.html { render :edit }
        format.json { render json: @cyclist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cyclists/1
  # DELETE /cyclists/1.json
  def destroy
    @cyclist.destroy
    respond_to do |format|
      format.html { redirect_to cyclists_url, notice: 'Cyclist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cyclist
      @cyclist = Cyclist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cyclist_params
      params.require(:cyclist).permit(:identificacion, :nombre, :usuario, :clave, :correo, :nomcontact, :correocontact)
    end
end

app/helpers/cyclists_helper.rb
module CyclistsHelper
end

app/views/cyclists/_form.html.erb
<%= form_for(cyclist) do |f| %>
  <% if cyclist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cyclist.errors.count, "error") %> prohibited this cyclist from being saved:</h2>

      <ul>
      <% cyclist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :identificacion %>
    <%= f.text_field :identificacion %>
  </div>

  <div class="field">
    <%= f.label :nombre %>
    <%= f.text_field :nombre %>
  </div>

  <div class="field">
    <%= f.label :usuario %>
    <%= f.text_field :usuario %>
  </div>

  <div class="field">
    <%= f.label :clave %>
    <%= f.text_field :clave %>
  </div>

  <div class="field">
    <%= f.label :correo %>
    <%= f.text_field :correo %>
  </div>

  <div class="field">
    <%= f.label :nomcontact %>
    <%= f.text_field :nomcontact %>
  </div>

  <div class="field">
    <%= f.label :correocontact %>
    <%= f.text_field :correocontact %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cyclists/edit.html.erb
<h1>Editing Cyclist</h1>

<%= render 'form', cyclist: @cyclist %>

<%= link_to 'Show', @cyclist %> |
<%= link_to 'Back', cyclists_path %>

app/views/cyclists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cyclists</h1>

<table>
  <thead>
    <tr>
      <th>Identificacion</th>
      <th>Nombre</th>
      <th>Usuario</th>
      <th>Clave</th>
      <th>Correo</th>
      <th>Nomcontact</th>
      <th>Correocontact</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cyclists.each do |cyclist| %>
      <tr>
        <td><%= cyclist.identificacion %></td>
        <td><%= cyclist.nombre %></td>
        <td><%= cyclist.usuario %></td>
        <td><%= cyclist.clave %></td>
        <td><%= cyclist.correo %></td>
        <td><%= cyclist.nomcontact %></td>
        <td><%= cyclist.correocontact %></td>
        <td><%= link_to 'Show', cyclist %></td>
        <td><%= link_to 'Edit', edit_cyclist_path(cyclist) %></td>
        <td><%= link_to 'Destroy', cyclist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cyclist', new_cyclist_path %>

app/views/cyclists/new.html.erb
<h1>New Cyclist</h1>

<%= render 'form', cyclist: @cyclist %>

<%= link_to 'Back', cyclists_path %>

app/views/cyclists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Identificacion:</strong>
  <%= @cyclist.identificacion %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @cyclist.nombre %>
</p>

<p>
  <strong>Usuario:</strong>
  <%= @cyclist.usuario %>
</p>

<p>
  <strong>Clave:</strong>
  <%= @cyclist.clave %>
</p>

<p>
  <strong>Correo:</strong>
  <%= @cyclist.correo %>
</p>

<p>
  <strong>Nomcontact:</strong>
  <%= @cyclist.nomcontact %>
</p>

<p>
  <strong>Correocontact:</strong>
  <%= @cyclist.correocontact %>
</p>

<%= link_to 'Edit', edit_cyclist_path(@cyclist) %> |
<%= link_to 'Back', cyclists_path %>